version: "3.8"
services:
  api:
    build:
      context: ./api
    ports:
      - "8000:8000"

    restart: unless-stopped

  web:
    build:
      context: ./web
    ports:
      - "5173:5173"

    restart: unless-stopped
